# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      duration: 1200,
      in_house: false
    )
    
    build_app(
      workspace: "Yela.xcworkspace",
      scheme: "Yela",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "Yela.ipa",
      export_options: {
        provisioningProfiles: {
          "com.yela.app" => "match AppStore com.yela.app"
        },
        signingStyle: "manual",
        teamID: "46Z55D38V7"
      }
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      notify_external_testers: false,
      api_key: api_key
    )
  end
end
