# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
prepare_react_native_project!

# Firebase requires modular headers
use_modular_headers!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FMB' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FMBTests' do
    inherit! :complete
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        # Fix for gRPC-Core and BoringSSL-GRPC template keyword errors
        if target.name == 'gRPC-Core' || target.name == 'gRPC-C++' || target.name == 'BoringSSL-GRPC'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -Wno-missing-template-arg-list-after-template-kw -Wno-deprecated-declarations'
        end
        
        # Fix for BoringSSL-GRPC -G flag issue
        if target.name == 'BoringSSL-GRPC'
          config.build_settings['OTHER_CFLAGS'] = '$(inherited) -GCC_WARN_INHIBIT_ALL_WARNINGS -w'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -GCC_WARN_INHIBIT_ALL_WARNINGS -w -Wno-missing-template-arg-list-after-template-kw -Wno-deprecated-declarations'
        end
      end
    end
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end